### ISSUE TITLE
not_x_content_exception: Compressor detection

### ISSUE THREAD

**Issue by brian-maloney** [EOSLaoMao/elasticsearch_plugin#6]
I am trying to run the latest version to see if performance is improved (I had the previous release running fine) but now I am getting this error on bulk inserts:

not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes

I have my bulk insert size set to only 10 for testing.  Here's the full error:

warn  2018-10-23T14:23:55.612 thread-13 exceptions.hpp:37             handle_elasticsearch ] elasticsearch exception, bulk exception, line 24, 3230006 bulk_fail_exception: Perform bulk get non zero errors
bulk perform errors: {"took":50,"errors":true,"items":[{"index":{"_index":"action_traces","_type":"_doc","_id":"rT1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},{"index":{"_index":"action_traces","_type":"_doc","_id":"rj1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},{"index":{"_index":"transaction_traces","_type":"_doc","_id":"rz1PoWYBpAN5--iPhhWo","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":108,"_primary_term":1,"status":201}},{"index":{"_index":"action_traces","_type":"_doc","_id":"sD1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},{"index":{"_index":"transaction_traces","_type":"_doc","_id":"sT1PoWYBpAN5--iPhhWo","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":118,"_primary_term":1,"status":201}},{"index":{"_index":"action_traces","_type":"_doc","_id":"sj1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},{"index":{"_index":"transaction_traces","_type":"_doc","_id":"sz1PoWYBpAN5--iPhhWo","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":119,"_primary_term":1,"status":201}},{"index":{"_index":"action_traces","_type":"_doc","_id":"tD1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},{"index":{"_index":"transaction_traces","_type":"_doc","_id":"tT1PoWYBpAN5--iPhhWo","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":109,"_primary_term":1,"status":201}},{"index":{"_index":"action_traces","_type":"_doc","_id":"tj1PoWYBpAN5--iPhhWo","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}}]}
    {"text":"{\"took\":50,\"errors\":true,\"items\":[{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"rT1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}},{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"rj1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}},{\"index\":{\"_index\":\"transaction_traces\",\"_type\":\"_doc\",\"_id\":\"rz1PoWYBpAN5--iPhhWo\",\"_version\":1,\"result\":\"created\",\"_shards\":{\"total\":2,\"successful\":2,\"failed\":0},\"_seq_no\":108,\"_primary_term\":1,\"status\":201}},{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"sD1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}},{\"index\":{\"_index\":\"transaction_traces\",\"_type\":\"_doc\",\"_id\":\"sT1PoWYBpAN5--iPhhWo\",\"_version\":1,\"result\":\"created\",\"_shards\":{\"total\":2,\"successful\":2,\"failed\":0},\"_seq_no\":118,\"_primary_term\":1,\"status\":201}},{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"sj1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}},{\"index\":{\"_index\":\"transaction_traces\",\"_type\":\"_doc\",\"_id\":\"sz1PoWYBpAN5--iPhhWo\",\"_version\":1,\"result\":\"created\",\"_shards\":{\"total\":2,\"successful\":2,\"failed\":0},\"_seq_no\":119,\"_primary_term\":1,\"status\":201}},{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"tD1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}},{\"index\":{\"_index\":\"transaction_traces\",\"_type\":\"_doc\",\"_id\":\"tT1PoWYBpAN5--iPhhWo\",\"_version\":1,\"result\":\"created\",\"_shards\":{\"total\":2,\"successful\":2,\"failed\":0},\"_seq_no\":109,\"_primary_term\":1,\"status\":201}},{\"index\":{\"_index\":\"action_traces\",\"_type\":\"_doc\",\"_id\":\"tj1PoWYBpAN5--iPhhWo\",\"status\":400,\"error\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}}}}]}"}

Any help would be appreciated.

**Comment by WLBF** [comment]
Never seen this before. Seem's like action trace index all failed, can you offer more information. like what exactly the mapping of action_trace index looks like. also version of your elasticsearch.

**Comment by brian-maloney** [comment]
I'm using the source direct from this repo, so here's the action_traces mapping:

```
static const std::string action_traces_mapping = R"(
{
    "mappings": {
        "_doc": {
            "properties": {
                "createAt": {
                    "type": "date"
                },
                "updateAt": {
                    "type": "date"
                },
                "receipt": {
                    "enabled": false
                },
                "act": {
                    "enabled": false
                },
                "account_ram_deltas": {
                    "enabled": false
                }
            }
        }
    }
}
)";
```
ES version is 6.4.2.

**Comment by brian-maloney** [comment]
I did a long run today (over 5 million blocks processed) and I never got a single document in the action_traces index.

Here's the error from elasticsearch's logs if it's helpful:

```
[2018-10-24T20:07:36,633][DEBUG][o.e.a.b.TransportShardBulkAction] [action_traces][3] failed to execute bulk item (index) BulkShardRequest [[action_traces][3]] containing [116] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
        at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:171) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:72) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:263) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:725) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:702) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:682) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$2(TransportShardBulkAction.java:560) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:579) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:558) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:141) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:247) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:124) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:111) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:73) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1017) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:995) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:101) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:356) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:296) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:958) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:955) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:271) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2249) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:967) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:97) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:317) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:292) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:251) [x-pack-security-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:309) [x-pack-security-6.4.2.jar:6.4.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:665) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:56) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:69) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:65) ~[elasticsearch-6.4.2.jar:6.4.2]
        ... 38 more
```

**Comment by brian-maloney** [comment]
Here's an example of the conversation between the client and elasticsearch: https://drive.google.com/file/d/10tZWtKSyQXLyT9kbApowqeBM7CFyo5JC/view?usp=sharing

**Comment by WLBF** [comment]
> Here's an example of the conversation between the client and elasticsearch: https://drive.google.com/file/d/10tZWtKSyQXLyT9kbApowqeBM7CFyo5JC/view?usp=sharing

```
{"index":{"_index":"action_traces","_type":"_doc","retry_on_conflict":100}}
[{"receipt":{"receiver":  ..................... }]
```
It seems that the elasticsearch exception caused by extra square brackets of the action_trace source line. It's very strange that the document get serialized to that form. In my case it look perfectly normal:
```
{"index":{"_index":"action_traces","_type":"_doc","retry_on_conflict":100}}
{"receipt":{"receiver":"eosio","act_digest":"f95697d1abf649...........................}
```
what is your eosio version, I test the 1.3.0, 1.4.1 it's both ok. Also, nodeos running in what env. I run it in ubuntu 18.04.

**Comment by brian-maloney** [comment]
I am currently running 1.4.1 on CentOS 7.  I had previously run on 1.3.1 and it worked, so I will try rebuilding that version and see if helps.

**Comment by brian-maloney** [comment]
I reverted to eos 1.3.2 with the current version of elasticsearch_plugin and it still could not insert any action_traces.

By reverting to eos 1.3.2 with elasticsearch_plugin commit id  7bfdf7aeba89f8aa40ab16e4cb30cb331663d297 it works again.  So it seems to be something related to the changes that came in with the multithreading.

**Comment by brian-maloney** [comment]
I rebuilt eosio 1.4.1 with the latest elasticsearch_plugin on Ubuntu 18.04 and it's successfully inserting action_traces, so this appears to be some CentOS 7 related issue.
